# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruitPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Display the score for the user linked')),
                ('fruitbool', models.BooleanField(default=None, help_text='Used to keep track of wether or not the user linked has said fruitful')),
            ],
        ),
        migrations.CreateModel(
            name='fruitVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=None, help_text='Indicates what the voter voted')),
                ('votee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='src.fruitPerson')),
                ('voter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votee', to='src.fruitPerson')),
            ],
        ),
        migrations.CreateModel(
            name='Munnygroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(help_text='Group name (exec or debate)', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Firstname', models.CharField(help_text='First name, (only 1, no spaces!)', max_length=20)),
                ('Lastname', models.CharField(help_text='Last name, (only 1, no spaces!)', max_length=20)),
                ('MUNID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rolegroup_primary', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rolegroup_secondary', to='src.Munnygroup')),
                ('rolegroup_secondary', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rolegroup_primary', to='src.Munnygroup')),
            ],
        ),
        migrations.AddField(
            model_name='fruitperson',
            name='userobject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='src.User'),
        ),
    ]
