# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruitPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Display the score for the user linked')),
                ('fruitbool', models.BooleanField(default=False, help_text='Used to keep track of wether or not the user linked has said fruitful')),
            ],
        ),
        migrations.CreateModel(
            name='fruitVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=None, help_text='Indicates what the voter voted')),
                ('votee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='src.fruitPerson')),
                ('voter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votee', to='src.fruitPerson')),
            ],
        ),
        migrations.CreateModel(
            name='Munnygroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(help_text='Group name (exec or debate)', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='speakerCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Name of the conutry speaking right here', max_length=35)),
                ('countryflag', models.CharField(help_text='URL for anchor links. Can be /src/static/images/<COUNTRYNAME>.png', max_length=100)),
                ('fruitsentiment', models.BooleanField(default=None, help_text='Change this sentiment after the fact')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Firstname', models.CharField(help_text='First name, (only 1, no spaces!)', max_length=20)),
                ('Lastname', models.CharField(help_text='Last name, (only 1, no spaces!)', max_length=20)),
                ('MUNID', models.CharField(help_text='This is the google docs jotform id thingy', max_length=20)),
                ('rolegroup_primary', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rolegroup_secondary', to='src.Munnygroup')),
                ('rolegroup_secondary', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rolegroup_primary', to='src.Munnygroup')),
            ],
        ),
        migrations.AddField(
            model_name='fruitperson',
            name='userobject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='src.User'),
        ),
    ]
