# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='munnyuser',
            name='FACEBOOKLINK',
            field=models.CharField(default=1, help_text='Facebbok ID', max_length=100),
            preserve_default=False,
        ),
    ]
