# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_munnyuser_facebooklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendfindermatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matcher', models.CharField(max_length=100)),
                ('matchee', models.CharField(max_length=100)),
            ],
        ),
    ]
