# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-25 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20180123_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Title of ticket goes here', max_length=50)),
                ('Text', models.TextField(help_text='Simply the body of the ticket.')),
                ('InitDate', models.DateTimeField(auto_now=True, help_text='Date and time of creation')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.User')),
            ],
        ),
        migrations.CreateModel(
            name='ticketreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(help_text='Simply the body of the ticket.')),
                ('InitDate', models.DateTimeField(auto_now=True, help_text='Date and time of creation')),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.ticket')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.User')),
            ],
        ),
    ]
