# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-11 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_fruitperson_speakerbool'),
    ]

    operations = [
        migrations.CreateModel(
            name='speakerCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Name of the conutry speaking right here', max_length=35)),
                ('countryflag', models.CharField(help_text='URL for anchor links. ', max_length=100)),
                ('fruitsentiment', models.BooleanField(default=None, help_text='Change this sentiment after the fact')),
            ],
        ),
        migrations.RemoveField(
            model_name='fruitperson',
            name='speakerbool',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
