# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_friendfindermatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendfindermatch',
            name='matchee',
            field=models.CharField(help_text="The person who is the 'matcher' is trying to match with", max_length=100),
        ),
        migrations.AlterField(
            model_name='friendfindermatch',
            name='matcher',
            field=models.CharField(help_text='The person who is trying to match to someone', max_length=100),
        ),
    ]
