# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20180111_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakercountry',
            name='countryflag',
            field=models.CharField(help_text='URL for anchor links. Can be /src/static/images/<COUNTRYNAME>.png', max_length=100),
        ),
    ]
