# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20180121_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_token', models.CharField(max_length=600, verbose_name='Facebook auth token')),
                ('facebook_id', models.CharField(max_length=20, verbose_name='Facebook id')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.User')),
            ],
        ),
    ]
