# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20180129_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='munnyuser',
            name='FACEBOOKLINK',
        ),
        migrations.RemoveField(
            model_name='munnyuser',
            name='rolegroup_secondary',
        ),
        migrations.AlterField(
            model_name='munnyuser',
            name='rolegroup_primary',
            field=models.CharField(choices=[('AD', 'Adstaff'), ('EX', 'Executive Team'), ('SO', 'Student Officer'), ('PR', 'Press'), ('DE', 'Delegate'), ('AM', 'Ambassador'), ('JA', 'Judge & Advocate'), ('JU', 'Judge')], max_length=2),
        ),
    ]
