# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20180129_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitvote',
            name='InitDate',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of creation'),
        ),
        migrations.AddField(
            model_name='speakercountry',
            name='voteEndTime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='munnyuser',
            name='MUNID',
            field=models.CharField(help_text='This is the google docs jotform id thingy', max_length=19),
        ),
    ]
