# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20180129_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitvote',
            name='InitDate',
            field=models.DateTimeField(default='Jan. 31, 2018, noon', help_text='Date and time of creation'),
        ),
    ]
